# Cloud Build configuration for automatic deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/solacesquad:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/solacesquad:latest'
      - './backend'
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/solacesquad:$COMMIT_SHA'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'solacesquad'
      - '--image'
      - 'gcr.io/$PROJECT_ID/solacesquad:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,DEBUG=False,DATABASE_URL=sqlite:///./soul_squad.db'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/solacesquad:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/solacesquad:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  
# Build timeout
timeout: 1200s
