steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'solacesquad-mirror'
      - '--region=us-central1'
      - '--update-secrets=SENDGRID_API_KEY=sendgrid-api-key:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,GOOGLE_CLIENT_ID=google-client-id:latest,RAZORPAY_KEY_ID=razorpay-key-id-mirror:latest,RAZORPAY_KEY_SECRET=razorpay-key-secret-mirror:latest,SECRET_KEY=secret-key-mirror:latest,SARVAM_API_KEY=sarvam-api-key:latest,MSG91_AUTH_KEY=msg91-auth-key:latest,TURN_SECRET=turn-secret:latest,DB_PASSWORD=db-password:latest,GEMINI_API_KEY=gemini-api-key:latest,EXOTEL_API_KEY=exotel-api-key:latest,EXOTEL_API_TOKEN=exotel-api-token:latest,EXOTEL_SID=exotel-sid:latest,EXOTEL_CALLER_ID=exotel-caller-id:latest'
logsBucket: 'gs://abiding-idea-485817-k2-build-logs'
timeout: 300s
