"""Fix_missing_columns

Revision ID: 5adc5decfa00
Revises: be4a38afdb48
Create Date: 2026-02-04 22:30:22.676243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5adc5decfa00'
down_revision: Union[str, None] = 'be4a38afdb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultant_profiles', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('consultant_profiles', sa.Column('is_profile_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultant_profiles', 'is_profile_completed')
    op.drop_column('consultant_profiles', 'is_approved')
    # ### end Alembic commands ###
